//go:build !noasm && amd64
// AUTO-GENERATED BY GOCC -- DO NOT EDIT

package bitmap

import "unsafe"

//go:noescape,nosplit
func _and_avx512(a unsafe.Pointer, b unsafe.Pointer, n uint64)

//go:noescape,nosplit
func _andn_avx512(a unsafe.Pointer, b unsafe.Pointer, n uint64)

//go:noescape,nosplit
func _or_avx512(a unsafe.Pointer, b unsafe.Pointer, n uint64)

//go:noescape,nosplit
func _xor_avx512(a unsafe.Pointer, b unsafe.Pointer, n uint64)

//go:noescape,nosplit
func _and_many_avx512(a unsafe.Pointer, b unsafe.Pointer, dims uint64)

//go:noescape,nosplit
func _andn_many_avx512(a unsafe.Pointer, b unsafe.Pointer, dims uint64)

//go:noescape,nosplit
func _or_many_avx512(a unsafe.Pointer, b unsafe.Pointer, dims uint64)

//go:noescape,nosplit
func _xor_many_avx512(a unsafe.Pointer, b unsafe.Pointer, dims uint64)
