//go:build !noasm && !darwin && arm64
// AUTO-GENERATED BY GOCC -- DO NOT EDIT

TEXT ·_and(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xa9bf7bfd  // stp	x29, x30, [sp, #-16]!
	WORD $0x910003fd  // mov	x29, sp
	WORD $0xb40002a2  // cbz	x2, .LBB0_7
	WORD $0xf100045f  // cmp	x2, #1
	WORD $0x54000100  // b.eq	.LBB0_4
	WORD $0xd37df048  // lsl	x8, x2, #3
	WORD $0x8b080029  // add	x9, x1, x8
	WORD $0xeb00013f  // cmp	x9, x0
	WORD $0x54000229  // b.ls	.LBB0_8
	WORD $0x8b080008  // add	x8, x0, x8
	WORD $0xeb01011f  // cmp	x8, x1
	WORD $0x540001c9  // b.ls	.LBB0_8

LBB0_4:
	WORD $0xaa1f03e8 // mov	x8, xzr

LBB0_5:
	WORD $0xd37df10a // lsl	x10, x8, #3
	WORD $0xcb080049 // sub	x9, x2, x8
	WORD $0x8b0a0008 // add	x8, x0, x10
	WORD $0x8b0a002a // add	x10, x1, x10

LBB0_6:
	WORD $0xf840854b // ldr	x11, [x10], #8
	WORD $0xf940010c // ldr	x12, [x8]
	WORD $0xf1000529 // subs	x9, x9, #1
	WORD $0x8a0b018b // and	x11, x12, x11
	WORD $0xf800850b // str	x11, [x8], #8
	WORD $0x54ffff61 // b.ne	.LBB0_6

LBB0_7:
	WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16
	WORD $0xd65f03c0 // ret

LBB0_8:
	WORD $0x927ff848 // and	x8, x2, #0xfffffffffffffffe
	WORD $0xaa0003ea // mov	x10, x0
	WORD $0xaa0803e9 // mov	x9, x8
	WORD $0xaa0103eb // mov	x11, x1

LBB0_9:
	WORD $0x3cc10560 // ldr	q0, [x11], #16
	WORD $0x3dc00141 // ldr	q1, [x10]
	WORD $0xf1000929 // subs	x9, x9, #2
	WORD $0x4e201c20 // and	v0.16b, v1.16b, v0.16b
	WORD $0x3c810540 // str	q0, [x10], #16
	WORD $0x54ffff61 // b.ne	.LBB0_9
	WORD $0xeb02011f // cmp	x8, x2
	WORD $0x54fffe60 // b.eq	.LBB0_7
	WORD $0x17ffffe8 // b	.LBB0_5

TEXT ·_andn(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xa9bf7bfd  // stp	x29, x30, [sp, #-16]!
	WORD $0x910003fd  // mov	x29, sp
	WORD $0xb40002a2  // cbz	x2, .LBB1_7
	WORD $0xf100045f  // cmp	x2, #1
	WORD $0x54000100  // b.eq	.LBB1_4
	WORD $0xd37df048  // lsl	x8, x2, #3
	WORD $0x8b080029  // add	x9, x1, x8
	WORD $0xeb00013f  // cmp	x9, x0
	WORD $0x54000229  // b.ls	.LBB1_8
	WORD $0x8b080008  // add	x8, x0, x8
	WORD $0xeb01011f  // cmp	x8, x1
	WORD $0x540001c9  // b.ls	.LBB1_8

LBB1_4:
	WORD $0xaa1f03e8 // mov	x8, xzr

LBB1_5:
	WORD $0xd37df10a // lsl	x10, x8, #3
	WORD $0xcb080049 // sub	x9, x2, x8
	WORD $0x8b0a0008 // add	x8, x0, x10
	WORD $0x8b0a002a // add	x10, x1, x10

LBB1_6:
	WORD $0xf840854b // ldr	x11, [x10], #8
	WORD $0xf940010c // ldr	x12, [x8]
	WORD $0xf1000529 // subs	x9, x9, #1
	WORD $0x8a2b018b // bic	x11, x12, x11
	WORD $0xf800850b // str	x11, [x8], #8
	WORD $0x54ffff61 // b.ne	.LBB1_6

LBB1_7:
	WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16
	WORD $0xd65f03c0 // ret

LBB1_8:
	WORD $0x927ff848 // and	x8, x2, #0xfffffffffffffffe
	WORD $0xaa0003ea // mov	x10, x0
	WORD $0xaa0803e9 // mov	x9, x8
	WORD $0xaa0103eb // mov	x11, x1

LBB1_9:
	WORD $0x3cc10560 // ldr	q0, [x11], #16
	WORD $0x3dc00141 // ldr	q1, [x10]
	WORD $0xf1000929 // subs	x9, x9, #2
	WORD $0x4e601c20 // bic	v0.16b, v1.16b, v0.16b
	WORD $0x3c810540 // str	q0, [x10], #16
	WORD $0x54ffff61 // b.ne	.LBB1_9
	WORD $0xeb02011f // cmp	x8, x2
	WORD $0x54fffe60 // b.eq	.LBB1_7
	WORD $0x17ffffe8 // b	.LBB1_5

TEXT ·_or(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xa9bf7bfd  // stp	x29, x30, [sp, #-16]!
	WORD $0x910003fd  // mov	x29, sp
	WORD $0xb40002a2  // cbz	x2, .LBB2_7
	WORD $0xf100045f  // cmp	x2, #1
	WORD $0x54000100  // b.eq	.LBB2_4
	WORD $0xd37df048  // lsl	x8, x2, #3
	WORD $0x8b080029  // add	x9, x1, x8
	WORD $0xeb00013f  // cmp	x9, x0
	WORD $0x54000229  // b.ls	.LBB2_8
	WORD $0x8b080008  // add	x8, x0, x8
	WORD $0xeb01011f  // cmp	x8, x1
	WORD $0x540001c9  // b.ls	.LBB2_8

LBB2_4:
	WORD $0xaa1f03e8 // mov	x8, xzr

LBB2_5:
	WORD $0xd37df10a // lsl	x10, x8, #3
	WORD $0xcb080049 // sub	x9, x2, x8
	WORD $0x8b0a0008 // add	x8, x0, x10
	WORD $0x8b0a002a // add	x10, x1, x10

LBB2_6:
	WORD $0xf840854b // ldr	x11, [x10], #8
	WORD $0xf940010c // ldr	x12, [x8]
	WORD $0xf1000529 // subs	x9, x9, #1
	WORD $0xaa0b018b // orr	x11, x12, x11
	WORD $0xf800850b // str	x11, [x8], #8
	WORD $0x54ffff61 // b.ne	.LBB2_6

LBB2_7:
	WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16
	WORD $0xd65f03c0 // ret

LBB2_8:
	WORD $0x927ff848 // and	x8, x2, #0xfffffffffffffffe
	WORD $0xaa0003ea // mov	x10, x0
	WORD $0xaa0803e9 // mov	x9, x8
	WORD $0xaa0103eb // mov	x11, x1

LBB2_9:
	WORD $0x3cc10560 // ldr	q0, [x11], #16
	WORD $0x3dc00141 // ldr	q1, [x10]
	WORD $0xf1000929 // subs	x9, x9, #2
	WORD $0x4ea01c20 // orr	v0.16b, v1.16b, v0.16b
	WORD $0x3c810540 // str	q0, [x10], #16
	WORD $0x54ffff61 // b.ne	.LBB2_9
	WORD $0xeb02011f // cmp	x8, x2
	WORD $0x54fffe60 // b.eq	.LBB2_7
	WORD $0x17ffffe8 // b	.LBB2_5

TEXT ·_xor(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xa9bf7bfd  // stp	x29, x30, [sp, #-16]!
	WORD $0x910003fd  // mov	x29, sp
	WORD $0xb40002a2  // cbz	x2, .LBB3_7
	WORD $0xf100045f  // cmp	x2, #1
	WORD $0x54000100  // b.eq	.LBB3_4
	WORD $0xd37df048  // lsl	x8, x2, #3
	WORD $0x8b080029  // add	x9, x1, x8
	WORD $0xeb00013f  // cmp	x9, x0
	WORD $0x54000229  // b.ls	.LBB3_8
	WORD $0x8b080008  // add	x8, x0, x8
	WORD $0xeb01011f  // cmp	x8, x1
	WORD $0x540001c9  // b.ls	.LBB3_8

LBB3_4:
	WORD $0xaa1f03e8 // mov	x8, xzr

LBB3_5:
	WORD $0xd37df10a // lsl	x10, x8, #3
	WORD $0xcb080049 // sub	x9, x2, x8
	WORD $0x8b0a0008 // add	x8, x0, x10
	WORD $0x8b0a002a // add	x10, x1, x10

LBB3_6:
	WORD $0xf840854b // ldr	x11, [x10], #8
	WORD $0xf940010c // ldr	x12, [x8]
	WORD $0xf1000529 // subs	x9, x9, #1
	WORD $0xca0b018b // eor	x11, x12, x11
	WORD $0xf800850b // str	x11, [x8], #8
	WORD $0x54ffff61 // b.ne	.LBB3_6

LBB3_7:
	WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16
	WORD $0xd65f03c0 // ret

LBB3_8:
	WORD $0x927ff848 // and	x8, x2, #0xfffffffffffffffe
	WORD $0xaa0003ea // mov	x10, x0
	WORD $0xaa0803e9 // mov	x9, x8
	WORD $0xaa0103eb // mov	x11, x1

LBB3_9:
	WORD $0x3cc10560 // ldr	q0, [x11], #16
	WORD $0x3dc00141 // ldr	q1, [x10]
	WORD $0xf1000929 // subs	x9, x9, #2
	WORD $0x6e201c20 // eor	v0.16b, v1.16b, v0.16b
	WORD $0x3c810540 // str	q0, [x10], #16
	WORD $0x54ffff61 // b.ne	.LBB3_9
	WORD $0xeb02011f // cmp	x8, x2
	WORD $0x54fffe60 // b.eq	.LBB3_7
	WORD $0x17ffffe8 // b	.LBB3_5

TEXT ·_and_many(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD dims+16(FP), R2
	WORD $0xa9ba7bfd     // stp	x29, x30, [sp, #-96]!
	WORD $0xf2407c48     // ands	x8, x2, #0xffffffff
	WORD $0xf9000bfb     // str	x27, [sp, #16]
	WORD $0xa90267fa     // stp	x26, x25, [sp, #32]
	WORD $0x910003fd     // mov	x29, sp
	WORD $0xa9035ff8     // stp	x24, x23, [sp, #48]
	WORD $0xa90457f6     // stp	x22, x21, [sp, #64]
	WORD $0xa9054ff4     // stp	x20, x19, [sp, #80]
	WORD $0x54000960     // b.eq	.LBB4_15
	WORD $0xd360fc4c     // lsr	x12, x2, #32
	WORD $0xaa1f03e9     // mov	x9, xzr
	WORD $0xf100059f     // cmp	x12, #1
	WORD $0xaa1f03ea     // mov	x10, xzr
	WORD $0xaa1f03eb     // mov	x11, xzr
	WORD $0xaa1f03f0     // mov	x16, xzr
	WORD $0x9a9f858d     // csinc	x13, x12, xzr, hi
	WORD $0x5280400e     // mov	w14, #512
	WORD $0xaa0003ef     // mov	x15, x0
	WORD $0x14000009     // b	.LBB4_3

LBB4_2:
	WORD $0x910801ce // add	x14, x14, #512
	WORD $0x9100056b // add	x11, x11, #1
	WORD $0xd108014a // sub	x10, x10, #512
	WORD $0x91400529 // add	x9, x9, #1, lsl #12
	WORD $0x914005ef // add	x15, x15, #1, lsl #12
	WORD $0xaa1103f0 // mov	x16, x17
	WORD $0xeb08023f // cmp	x17, x8
	WORD $0x54000722 // b.hs	.LBB4_15

LBB4_3:
	WORD $0xeb0801df // cmp	x14, x8
	WORD $0x91080211 // add	x17, x16, #512
	WORD $0x9a8831d2 // csel	x18, x14, x8, lo
	WORD $0xb4fffeac // cbz	x12, .LBB4_2
	WORD $0xcb0b2643 // sub	x3, x18, x11, lsl #9
	WORD $0xd374cd64 // lsl	x4, x11, #12
	WORD $0x8b0a0245 // add	x5, x18, x10
	WORD $0xeb08023f // cmp	x17, x8
	WORD $0x8b030c86 // add	x6, x4, x3, lsl #3
	WORD $0x927ff874 // and	x20, x3, #0xfffffffffffffffe
	WORD $0xaa1f03e2 // mov	x2, xzr
	WORD $0x927ff8a5 // and	x5, x5, #0xfffffffffffffffe
	WORD $0x8b040007 // add	x7, x0, x4
	WORD $0x8b0000d3 // add	x19, x6, x0
	WORD $0x9a883235 // csel	x21, x17, x8, lo
	WORD $0x8b140216 // add	x22, x16, x20
	WORD $0x14000004 // b	.LBB4_6

LBB4_5:
	WORD $0x91000442 // add	x2, x2, #1
	WORD $0xeb0d005f // cmp	x2, x13
	WORD $0x54fffca0 // b.eq	.LBB4_2

LBB4_6:
	WORD $0xeb15021f // cmp	x16, x21
	WORD $0x54ffff82 // b.hs	.LBB4_5
	WORD $0xf8627837 // ldr	x23, [x1, x2, lsl #3]
	WORD $0xaa1003f9 // mov	x25, x16
	WORD $0xf100087f // cmp	x3, #2
	WORD $0x54000283 // b.lo	.LBB4_13
	WORD $0x8b0602f8 // add	x24, x23, x6
	WORD $0xeb1800ff // cmp	x7, x24
	WORD $0x540000a2 // b.hs	.LBB4_10
	WORD $0xaa1003f9 // mov	x25, x16
	WORD $0x8b0402f8 // add	x24, x23, x4
	WORD $0xeb13031f // cmp	x24, x19
	WORD $0x540001a3 // b.lo	.LBB4_13

LBB4_10:
	WORD $0x8b0902f8 // add	x24, x23, x9
	WORD $0xaa0f03f9 // mov	x25, x15
	WORD $0xaa0503fa // mov	x26, x5

LBB4_11:
	WORD $0x3cc10700 // ldr	q0, [x24], #16
	WORD $0x3dc00321 // ldr	q1, [x25]
	WORD $0xf1000b5a // subs	x26, x26, #2
	WORD $0x4e201c20 // and	v0.16b, v1.16b, v0.16b
	WORD $0x3c810720 // str	q0, [x25], #16
	WORD $0x54ffff61 // b.ne	.LBB4_11
	WORD $0xaa1603f9 // mov	x25, x22
	WORD $0xeb14007f // cmp	x3, x20
	WORD $0x54fffca0 // b.eq	.LBB4_5

LBB4_13:
	WORD $0xd37df33a // lsl	x26, x25, #3
	WORD $0xcb190258 // sub	x24, x18, x25
	WORD $0x8b1a0019 // add	x25, x0, x26
	WORD $0x8b1a02f7 // add	x23, x23, x26

LBB4_14:
	WORD $0xf84086fa // ldr	x26, [x23], #8
	WORD $0xf940033b // ldr	x27, [x25]
	WORD $0xf1000718 // subs	x24, x24, #1
	WORD $0x8a1a037a // and	x26, x27, x26
	WORD $0xf800873a // str	x26, [x25], #8
	WORD $0x54ffff61 // b.ne	.LBB4_14
	WORD $0x17ffffda // b	.LBB4_5

LBB4_15:
	WORD $0xa9454ff4 // ldp	x20, x19, [sp, #80]
	WORD $0xa94457f6 // ldp	x22, x21, [sp, #64]
	WORD $0xa9435ff8 // ldp	x24, x23, [sp, #48]
	WORD $0xa94267fa // ldp	x26, x25, [sp, #32]
	WORD $0xf9400bfb // ldr	x27, [sp, #16]
	WORD $0xa8c67bfd // ldp	x29, x30, [sp], #96
	WORD $0xd65f03c0 // ret

TEXT ·_andn_many(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD dims+16(FP), R2
	WORD $0xa9ba7bfd     // stp	x29, x30, [sp, #-96]!
	WORD $0xf2407c48     // ands	x8, x2, #0xffffffff
	WORD $0xf9000bfb     // str	x27, [sp, #16]
	WORD $0xa90267fa     // stp	x26, x25, [sp, #32]
	WORD $0x910003fd     // mov	x29, sp
	WORD $0xa9035ff8     // stp	x24, x23, [sp, #48]
	WORD $0xa90457f6     // stp	x22, x21, [sp, #64]
	WORD $0xa9054ff4     // stp	x20, x19, [sp, #80]
	WORD $0x54000960     // b.eq	.LBB5_15
	WORD $0xd360fc4c     // lsr	x12, x2, #32
	WORD $0xaa1f03e9     // mov	x9, xzr
	WORD $0xf100059f     // cmp	x12, #1
	WORD $0xaa1f03ea     // mov	x10, xzr
	WORD $0xaa1f03eb     // mov	x11, xzr
	WORD $0xaa1f03f0     // mov	x16, xzr
	WORD $0x9a9f858d     // csinc	x13, x12, xzr, hi
	WORD $0x5280400e     // mov	w14, #512
	WORD $0xaa0003ef     // mov	x15, x0
	WORD $0x14000009     // b	.LBB5_3

LBB5_2:
	WORD $0x910801ce // add	x14, x14, #512
	WORD $0x9100056b // add	x11, x11, #1
	WORD $0xd108014a // sub	x10, x10, #512
	WORD $0x91400529 // add	x9, x9, #1, lsl #12
	WORD $0x914005ef // add	x15, x15, #1, lsl #12
	WORD $0xaa1103f0 // mov	x16, x17
	WORD $0xeb08023f // cmp	x17, x8
	WORD $0x54000722 // b.hs	.LBB5_15

LBB5_3:
	WORD $0xeb0801df // cmp	x14, x8
	WORD $0x91080211 // add	x17, x16, #512
	WORD $0x9a8831d2 // csel	x18, x14, x8, lo
	WORD $0xb4fffeac // cbz	x12, .LBB5_2
	WORD $0xcb0b2643 // sub	x3, x18, x11, lsl #9
	WORD $0xd374cd64 // lsl	x4, x11, #12
	WORD $0x8b0a0245 // add	x5, x18, x10
	WORD $0xeb08023f // cmp	x17, x8
	WORD $0x8b030c86 // add	x6, x4, x3, lsl #3
	WORD $0x927ff874 // and	x20, x3, #0xfffffffffffffffe
	WORD $0xaa1f03e2 // mov	x2, xzr
	WORD $0x927ff8a5 // and	x5, x5, #0xfffffffffffffffe
	WORD $0x8b040007 // add	x7, x0, x4
	WORD $0x8b0000d3 // add	x19, x6, x0
	WORD $0x9a883235 // csel	x21, x17, x8, lo
	WORD $0x8b140216 // add	x22, x16, x20
	WORD $0x14000004 // b	.LBB5_6

LBB5_5:
	WORD $0x91000442 // add	x2, x2, #1
	WORD $0xeb0d005f // cmp	x2, x13
	WORD $0x54fffca0 // b.eq	.LBB5_2

LBB5_6:
	WORD $0xeb15021f // cmp	x16, x21
	WORD $0x54ffff82 // b.hs	.LBB5_5
	WORD $0xf8627837 // ldr	x23, [x1, x2, lsl #3]
	WORD $0xaa1003f9 // mov	x25, x16
	WORD $0xf100087f // cmp	x3, #2
	WORD $0x54000283 // b.lo	.LBB5_13
	WORD $0x8b0602f8 // add	x24, x23, x6
	WORD $0xeb1800ff // cmp	x7, x24
	WORD $0x540000a2 // b.hs	.LBB5_10
	WORD $0xaa1003f9 // mov	x25, x16
	WORD $0x8b0402f8 // add	x24, x23, x4
	WORD $0xeb13031f // cmp	x24, x19
	WORD $0x540001a3 // b.lo	.LBB5_13

LBB5_10:
	WORD $0x8b0902f8 // add	x24, x23, x9
	WORD $0xaa0f03f9 // mov	x25, x15
	WORD $0xaa0503fa // mov	x26, x5

LBB5_11:
	WORD $0x3cc10700 // ldr	q0, [x24], #16
	WORD $0x3dc00321 // ldr	q1, [x25]
	WORD $0xf1000b5a // subs	x26, x26, #2
	WORD $0x4e601c20 // bic	v0.16b, v1.16b, v0.16b
	WORD $0x3c810720 // str	q0, [x25], #16
	WORD $0x54ffff61 // b.ne	.LBB5_11
	WORD $0xaa1603f9 // mov	x25, x22
	WORD $0xeb14007f // cmp	x3, x20
	WORD $0x54fffca0 // b.eq	.LBB5_5

LBB5_13:
	WORD $0xd37df33a // lsl	x26, x25, #3
	WORD $0xcb190258 // sub	x24, x18, x25
	WORD $0x8b1a0019 // add	x25, x0, x26
	WORD $0x8b1a02f7 // add	x23, x23, x26

LBB5_14:
	WORD $0xf84086fa // ldr	x26, [x23], #8
	WORD $0xf940033b // ldr	x27, [x25]
	WORD $0xf1000718 // subs	x24, x24, #1
	WORD $0x8a3a037a // bic	x26, x27, x26
	WORD $0xf800873a // str	x26, [x25], #8
	WORD $0x54ffff61 // b.ne	.LBB5_14
	WORD $0x17ffffda // b	.LBB5_5

LBB5_15:
	WORD $0xa9454ff4 // ldp	x20, x19, [sp, #80]
	WORD $0xa94457f6 // ldp	x22, x21, [sp, #64]
	WORD $0xa9435ff8 // ldp	x24, x23, [sp, #48]
	WORD $0xa94267fa // ldp	x26, x25, [sp, #32]
	WORD $0xf9400bfb // ldr	x27, [sp, #16]
	WORD $0xa8c67bfd // ldp	x29, x30, [sp], #96
	WORD $0xd65f03c0 // ret

TEXT ·_or_many(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD dims+16(FP), R2
	WORD $0xa9ba7bfd     // stp	x29, x30, [sp, #-96]!
	WORD $0xf2407c48     // ands	x8, x2, #0xffffffff
	WORD $0xf9000bfb     // str	x27, [sp, #16]
	WORD $0xa90267fa     // stp	x26, x25, [sp, #32]
	WORD $0x910003fd     // mov	x29, sp
	WORD $0xa9035ff8     // stp	x24, x23, [sp, #48]
	WORD $0xa90457f6     // stp	x22, x21, [sp, #64]
	WORD $0xa9054ff4     // stp	x20, x19, [sp, #80]
	WORD $0x54000960     // b.eq	.LBB6_15
	WORD $0xd360fc4c     // lsr	x12, x2, #32
	WORD $0xaa1f03e9     // mov	x9, xzr
	WORD $0xf100059f     // cmp	x12, #1
	WORD $0xaa1f03ea     // mov	x10, xzr
	WORD $0xaa1f03eb     // mov	x11, xzr
	WORD $0xaa1f03f0     // mov	x16, xzr
	WORD $0x9a9f858d     // csinc	x13, x12, xzr, hi
	WORD $0x5280400e     // mov	w14, #512
	WORD $0xaa0003ef     // mov	x15, x0
	WORD $0x14000009     // b	.LBB6_3

LBB6_2:
	WORD $0x910801ce // add	x14, x14, #512
	WORD $0x9100056b // add	x11, x11, #1
	WORD $0xd108014a // sub	x10, x10, #512
	WORD $0x91400529 // add	x9, x9, #1, lsl #12
	WORD $0x914005ef // add	x15, x15, #1, lsl #12
	WORD $0xaa1103f0 // mov	x16, x17
	WORD $0xeb08023f // cmp	x17, x8
	WORD $0x54000722 // b.hs	.LBB6_15

LBB6_3:
	WORD $0xeb0801df // cmp	x14, x8
	WORD $0x91080211 // add	x17, x16, #512
	WORD $0x9a8831d2 // csel	x18, x14, x8, lo
	WORD $0xb4fffeac // cbz	x12, .LBB6_2
	WORD $0xcb0b2643 // sub	x3, x18, x11, lsl #9
	WORD $0xd374cd64 // lsl	x4, x11, #12
	WORD $0x8b0a0245 // add	x5, x18, x10
	WORD $0xeb08023f // cmp	x17, x8
	WORD $0x8b030c86 // add	x6, x4, x3, lsl #3
	WORD $0x927ff874 // and	x20, x3, #0xfffffffffffffffe
	WORD $0xaa1f03e2 // mov	x2, xzr
	WORD $0x927ff8a5 // and	x5, x5, #0xfffffffffffffffe
	WORD $0x8b040007 // add	x7, x0, x4
	WORD $0x8b0000d3 // add	x19, x6, x0
	WORD $0x9a883235 // csel	x21, x17, x8, lo
	WORD $0x8b140216 // add	x22, x16, x20
	WORD $0x14000004 // b	.LBB6_6

LBB6_5:
	WORD $0x91000442 // add	x2, x2, #1
	WORD $0xeb0d005f // cmp	x2, x13
	WORD $0x54fffca0 // b.eq	.LBB6_2

LBB6_6:
	WORD $0xeb15021f // cmp	x16, x21
	WORD $0x54ffff82 // b.hs	.LBB6_5
	WORD $0xf8627837 // ldr	x23, [x1, x2, lsl #3]
	WORD $0xaa1003f9 // mov	x25, x16
	WORD $0xf100087f // cmp	x3, #2
	WORD $0x54000283 // b.lo	.LBB6_13
	WORD $0x8b0602f8 // add	x24, x23, x6
	WORD $0xeb1800ff // cmp	x7, x24
	WORD $0x540000a2 // b.hs	.LBB6_10
	WORD $0xaa1003f9 // mov	x25, x16
	WORD $0x8b0402f8 // add	x24, x23, x4
	WORD $0xeb13031f // cmp	x24, x19
	WORD $0x540001a3 // b.lo	.LBB6_13

LBB6_10:
	WORD $0x8b0902f8 // add	x24, x23, x9
	WORD $0xaa0f03f9 // mov	x25, x15
	WORD $0xaa0503fa // mov	x26, x5

LBB6_11:
	WORD $0x3cc10700 // ldr	q0, [x24], #16
	WORD $0x3dc00321 // ldr	q1, [x25]
	WORD $0xf1000b5a // subs	x26, x26, #2
	WORD $0x4ea01c20 // orr	v0.16b, v1.16b, v0.16b
	WORD $0x3c810720 // str	q0, [x25], #16
	WORD $0x54ffff61 // b.ne	.LBB6_11
	WORD $0xaa1603f9 // mov	x25, x22
	WORD $0xeb14007f // cmp	x3, x20
	WORD $0x54fffca0 // b.eq	.LBB6_5

LBB6_13:
	WORD $0xd37df33a // lsl	x26, x25, #3
	WORD $0xcb190258 // sub	x24, x18, x25
	WORD $0x8b1a0019 // add	x25, x0, x26
	WORD $0x8b1a02f7 // add	x23, x23, x26

LBB6_14:
	WORD $0xf84086fa // ldr	x26, [x23], #8
	WORD $0xf940033b // ldr	x27, [x25]
	WORD $0xf1000718 // subs	x24, x24, #1
	WORD $0xaa1a037a // orr	x26, x27, x26
	WORD $0xf800873a // str	x26, [x25], #8
	WORD $0x54ffff61 // b.ne	.LBB6_14
	WORD $0x17ffffda // b	.LBB6_5

LBB6_15:
	WORD $0xa9454ff4 // ldp	x20, x19, [sp, #80]
	WORD $0xa94457f6 // ldp	x22, x21, [sp, #64]
	WORD $0xa9435ff8 // ldp	x24, x23, [sp, #48]
	WORD $0xa94267fa // ldp	x26, x25, [sp, #32]
	WORD $0xf9400bfb // ldr	x27, [sp, #16]
	WORD $0xa8c67bfd // ldp	x29, x30, [sp], #96
	WORD $0xd65f03c0 // ret

TEXT ·_xor_many(SB), $0-32
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD dims+16(FP), R2
	WORD $0xa9ba7bfd     // stp	x29, x30, [sp, #-96]!
	WORD $0xf2407c48     // ands	x8, x2, #0xffffffff
	WORD $0xf9000bfb     // str	x27, [sp, #16]
	WORD $0xa90267fa     // stp	x26, x25, [sp, #32]
	WORD $0x910003fd     // mov	x29, sp
	WORD $0xa9035ff8     // stp	x24, x23, [sp, #48]
	WORD $0xa90457f6     // stp	x22, x21, [sp, #64]
	WORD $0xa9054ff4     // stp	x20, x19, [sp, #80]
	WORD $0x54000960     // b.eq	.LBB7_15
	WORD $0xd360fc4c     // lsr	x12, x2, #32
	WORD $0xaa1f03e9     // mov	x9, xzr
	WORD $0xf100059f     // cmp	x12, #1
	WORD $0xaa1f03ea     // mov	x10, xzr
	WORD $0xaa1f03eb     // mov	x11, xzr
	WORD $0xaa1f03f0     // mov	x16, xzr
	WORD $0x9a9f858d     // csinc	x13, x12, xzr, hi
	WORD $0x5280400e     // mov	w14, #512
	WORD $0xaa0003ef     // mov	x15, x0
	WORD $0x14000009     // b	.LBB7_3

LBB7_2:
	WORD $0x910801ce // add	x14, x14, #512
	WORD $0x9100056b // add	x11, x11, #1
	WORD $0xd108014a // sub	x10, x10, #512
	WORD $0x91400529 // add	x9, x9, #1, lsl #12
	WORD $0x914005ef // add	x15, x15, #1, lsl #12
	WORD $0xaa1103f0 // mov	x16, x17
	WORD $0xeb08023f // cmp	x17, x8
	WORD $0x54000722 // b.hs	.LBB7_15

LBB7_3:
	WORD $0xeb0801df // cmp	x14, x8
	WORD $0x91080211 // add	x17, x16, #512
	WORD $0x9a8831d2 // csel	x18, x14, x8, lo
	WORD $0xb4fffeac // cbz	x12, .LBB7_2
	WORD $0xcb0b2643 // sub	x3, x18, x11, lsl #9
	WORD $0xd374cd64 // lsl	x4, x11, #12
	WORD $0x8b0a0245 // add	x5, x18, x10
	WORD $0xeb08023f // cmp	x17, x8
	WORD $0x8b030c86 // add	x6, x4, x3, lsl #3
	WORD $0x927ff874 // and	x20, x3, #0xfffffffffffffffe
	WORD $0xaa1f03e2 // mov	x2, xzr
	WORD $0x927ff8a5 // and	x5, x5, #0xfffffffffffffffe
	WORD $0x8b040007 // add	x7, x0, x4
	WORD $0x8b0000d3 // add	x19, x6, x0
	WORD $0x9a883235 // csel	x21, x17, x8, lo
	WORD $0x8b140216 // add	x22, x16, x20
	WORD $0x14000004 // b	.LBB7_6

LBB7_5:
	WORD $0x91000442 // add	x2, x2, #1
	WORD $0xeb0d005f // cmp	x2, x13
	WORD $0x54fffca0 // b.eq	.LBB7_2

LBB7_6:
	WORD $0xeb15021f // cmp	x16, x21
	WORD $0x54ffff82 // b.hs	.LBB7_5
	WORD $0xf8627837 // ldr	x23, [x1, x2, lsl #3]
	WORD $0xaa1003f9 // mov	x25, x16
	WORD $0xf100087f // cmp	x3, #2
	WORD $0x54000283 // b.lo	.LBB7_13
	WORD $0x8b0602f8 // add	x24, x23, x6
	WORD $0xeb1800ff // cmp	x7, x24
	WORD $0x540000a2 // b.hs	.LBB7_10
	WORD $0xaa1003f9 // mov	x25, x16
	WORD $0x8b0402f8 // add	x24, x23, x4
	WORD $0xeb13031f // cmp	x24, x19
	WORD $0x540001a3 // b.lo	.LBB7_13

LBB7_10:
	WORD $0x8b0902f8 // add	x24, x23, x9
	WORD $0xaa0f03f9 // mov	x25, x15
	WORD $0xaa0503fa // mov	x26, x5

LBB7_11:
	WORD $0x3cc10700 // ldr	q0, [x24], #16
	WORD $0x3dc00321 // ldr	q1, [x25]
	WORD $0xf1000b5a // subs	x26, x26, #2
	WORD $0x6e201c20 // eor	v0.16b, v1.16b, v0.16b
	WORD $0x3c810720 // str	q0, [x25], #16
	WORD $0x54ffff61 // b.ne	.LBB7_11
	WORD $0xaa1603f9 // mov	x25, x22
	WORD $0xeb14007f // cmp	x3, x20
	WORD $0x54fffca0 // b.eq	.LBB7_5

LBB7_13:
	WORD $0xd37df33a // lsl	x26, x25, #3
	WORD $0xcb190258 // sub	x24, x18, x25
	WORD $0x8b1a0019 // add	x25, x0, x26
	WORD $0x8b1a02f7 // add	x23, x23, x26

LBB7_14:
	WORD $0xf84086fa // ldr	x26, [x23], #8
	WORD $0xf940033b // ldr	x27, [x25]
	WORD $0xf1000718 // subs	x24, x24, #1
	WORD $0xca1a037a // eor	x26, x27, x26
	WORD $0xf800873a // str	x26, [x25], #8
	WORD $0x54ffff61 // b.ne	.LBB7_14
	WORD $0x17ffffda // b	.LBB7_5

LBB7_15:
	WORD $0xa9454ff4 // ldp	x20, x19, [sp, #80]
	WORD $0xa94457f6 // ldp	x22, x21, [sp, #64]
	WORD $0xa9435ff8 // ldp	x24, x23, [sp, #48]
	WORD $0xa94267fa // ldp	x26, x25, [sp, #32]
	WORD $0xf9400bfb // ldr	x27, [sp, #16]
	WORD $0xa8c67bfd // ldp	x29, x30, [sp], #96
	WORD $0xd65f03c0 // ret

TEXT ·_count(SB), $0-32
	MOVD a+0(FP), R0
	MOVD size+8(FP), R1
	MOVD result+16(FP), R2
	WORD $0xa9bf7bfd       // stp	x29, x30, [sp, #-16]!
	WORD $0xaa1f03e8       // mov	x8, xzr
	WORD $0x910003fd       // mov	x29, sp
	WORD $0xb4000101       // cbz	x1, .LBB8_2

LBB8_1:
	WORD $0xfc408400 // ldr	d0, [x0], #8
	WORD $0xf1000421 // subs	x1, x1, #1
	WORD $0x0e205800 // cnt	v0.8b, v0.8b
	WORD $0x2e303800 // uaddlv	h0, v0.8b
	WORD $0x1e260009 // fmov	w9, s0
	WORD $0x8b080128 // add	x8, x9, x8
	WORD $0x54ffff41 // b.ne	.LBB8_1

LBB8_2:
	WORD $0xf9000048 // str	x8, [x2]
	WORD $0xa8c17bfd // ldp	x29, x30, [sp], #16
	WORD $0xd65f03c0 // ret
