// Code generated by command: go run amd64.go -out ../simd_amd64.s -stubs ../simd_amd64.go -pkg=bitmap. DO NOT EDIT.

// +build !appengine
// +build !noasm
// +build gc

package bitmap

// x64count counts the bits set to one
//go:noescape
func x64count(a []uint64) uint64

// x64and (AND) computes the intersection between two slices and stores the result in the first one
//go:noescape
func x64and(a []uint64, b []uint64)

// x64andn (AND NOT) computes the difference between two slices and stores the result in the first one
//go:noescape
func x64andn(a []uint64, b []uint64)

// x64or (OR) computes the union between two slices and stores the result in the first one
//go:noescape
func x64or(a []uint64, b []uint64)

// x64xor (XOR) computes the symmetric difference between two slices and stores the result in the first one
//go:noescape
func x64xor(a []uint64, b []uint64)
