// Code generated by command: go run amd64.go -out ../simd_amd64.s -stubs ../simd_amd64.go -pkg=bitmap. DO NOT EDIT.

//go:build !appengine && !noasm && gc
// +build !appengine,!noasm,gc

package bitmap

// x64count counts the bits set to one
//go:noescape
func x64count(a []uint64) uint64

//go:noescape
func x64and1(a []uint64, b []uint64)

//go:noescape
func x64andn1(a []uint64, b []uint64)

//go:noescape
func x64or1(a []uint64, b []uint64)

//go:noescape
func x64xor1(a []uint64, b []uint64)

//go:noescape
func x64and2(a []uint64, b []uint64, c []uint64)

//go:noescape
func x64andn2(a []uint64, b []uint64, c []uint64)

//go:noescape
func x64or2(a []uint64, b []uint64, c []uint64)

//go:noescape
func x64xor2(a []uint64, b []uint64, c []uint64)

//go:noescape
func x64and3(a []uint64, b []uint64, c []uint64, d []uint64)

//go:noescape
func x64andn3(a []uint64, b []uint64, c []uint64, d []uint64)

//go:noescape
func x64or3(a []uint64, b []uint64, c []uint64, d []uint64)

//go:noescape
func x64xor3(a []uint64, b []uint64, c []uint64, d []uint64)

//go:noescape
func x64and4(a []uint64, b []uint64, c []uint64, d []uint64, e []uint64)

//go:noescape
func x64andn4(a []uint64, b []uint64, c []uint64, d []uint64, e []uint64)

//go:noescape
func x64or4(a []uint64, b []uint64, c []uint64, d []uint64, e []uint64)

//go:noescape
func x64xor4(a []uint64, b []uint64, c []uint64, d []uint64, e []uint64)
