//go:build !noasm && !darwin && arm64
// AUTO-GENERATED BY GOCC -- DO NOT EDIT

package bitmap

import "unsafe"

//go:noescape,nosplit
func _and(a unsafe.Pointer, b unsafe.Pointer, n uint64)

//go:noescape,nosplit
func _andn(a unsafe.Pointer, b unsafe.Pointer, n uint64)

//go:noescape,nosplit
func _or(a unsafe.Pointer, b unsafe.Pointer, n uint64)

//go:noescape,nosplit
func _xor(a unsafe.Pointer, b unsafe.Pointer, n uint64)

//go:noescape,nosplit
func _and_many(a unsafe.Pointer, b unsafe.Pointer, dims uint64)

//go:noescape,nosplit
func _andn_many(a unsafe.Pointer, b unsafe.Pointer, dims uint64)

//go:noescape,nosplit
func _or_many(a unsafe.Pointer, b unsafe.Pointer, dims uint64)

//go:noescape,nosplit
func _xor_many(a unsafe.Pointer, b unsafe.Pointer, dims uint64)

//go:noescape,nosplit
func _count(a unsafe.Pointer, size uint64, result unsafe.Pointer)
