// Code generated by command: go run asm.go -out simd.s -stubs stub.go. DO NOT EDIT.

package simd

// And And computes the intersection between two slices and stores the result in the first one
func And(a []uint64, b []uint64)

// AndNot computes the difference between two slices and stores the result in the first one
func AndNot(a []uint64, b []uint64)

// Or computes the union between two slices and stores the result in the first one
func Or(a []uint64, b []uint64)

// Xor computes the symmetric difference between two slices and stores the result in the first one
func Xor(a []uint64, b []uint64)
